import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      position: 'relative',
    },
    camera: {
      flex: 1,
    },
    maskContainer: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 10,
    },
    mask: {
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
      position: 'absolute',
    },
    maskTop: {
      top: 0,
      left: 0,
      right: 0,
      height: '30%',
    },
    maskBottom: {
      bottom: 0,
      left: 0,
      right: 0,
      height: '45%',
    },
    maskLeft: {
      top: '30%',
      bottom: '45%',
      left: 0,
      width: '15%',
    },
    maskRight: {
      top: '30%',
      bottom: '45%',
      right: 0,
      width: '15%',
    },
    scanBox: {
      position: 'absolute',
      top: '30%',
      left: '15%',
      width: '70%',
      height: '25%',
      zIndex: 15,
    },
    scanCorner: {
      position: 'absolute',
      width: 30,
      height: 30,
      borderColor: '#fff',
      borderWidth: 3,
      borderTopLeftRadius: 10,
    },
    topRight: {
      left: undefined,
      right: 0,
      borderTopLeftRadius: 0,
      borderTopRightRadius: 10,
    },
    bottomLeft: {
      top: undefined,
      bottom: 0,
      borderTopLeftRadius: 0,
      borderBottomLeftRadius: 10,
    },
    bottomRight: {
      top: undefined,
      bottom: 0,
      left: undefined,
      right: 0,
      borderTopLeftRadius: 0,
      borderTopRightRadius: 0,
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 10,
    },
    hintContainer: {
      position: 'absolute',
      top: '58%',
      left: '15%',
      width: '70%',
      padding: Spacing.md,
      borderRadius: BorderRadius.lg,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      alignItems: 'center',
      zIndex: 15,
    },
    flipButton: {
      position: 'absolute',
      bottom: 180,
      left: '50%',
      transform: [{ translateX: -25 }],
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: 'rgba(255, 255, 255, 0.3)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 20,
    },
    captureButton: {
      position: 'absolute',
      bottom: 80,
      left: '50%',
      transform: [{ translateX: -35 }],
      width: 70,
      height: 70,
      borderRadius: 35,
      backgroundColor: '#fff',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 20,
    },
    captureButtonInner: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: theme.primary,
    },
    cancelButtonTop: {
      position: 'absolute',
      top: 50,
      right: 20,
      padding: Spacing.md,
      zIndex: 20,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    permissionContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: Spacing.xl,
    },
    permissionIcon: {
      marginBottom: Spacing.lg,
    },
    permissionTitle: {
      marginBottom: Spacing.md,
      textAlign: 'center',
    },
    permissionText: {
      marginBottom: Spacing.xl,
      textAlign: 'center',
    },
    permissionButton: {
      backgroundColor: theme.primary,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.xl,
      borderRadius: BorderRadius.lg,
      marginBottom: Spacing.md,
    },
    cancelButton: {
      paddingVertical: Spacing.md,
    },
    scanningOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 100,
    },
    scanningText: {
      marginTop: Spacing.lg,
    },
    resultsOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.9)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: Spacing.xl,
      zIndex: 100,
    },
    resultsContainer: {
      width: '100%',
      maxHeight: '80%',
      backgroundColor: '#fff',
      borderRadius: BorderRadius.xl,
      overflow: 'hidden',
      display: 'flex',
      flexDirection: 'column',
    },
    resultsHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: Spacing.lg,
      backgroundColor: '#fff',
      borderBottomWidth: 1,
      borderBottomColor: '#e0e0e0',
    },
    resultsTitle: {
      flex: 1,
      fontSize: 18,
      fontWeight: 'bold',
      color: '#000',
    },
    closeButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: '#fff',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: '#e0e0e0',
    },
    resultsList: {
      flex: 1,
      padding: Spacing.md,
    },
    wordItem: {
      padding: Spacing.md,
      marginBottom: Spacing.md,
      backgroundColor: '#f9f9f9',
      borderRadius: BorderRadius.lg,
      borderWidth: 1,
      borderColor: '#e0e0e0',
    },
    wordItemHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.sm,
    },
    rescanButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.xl,
      backgroundColor: '#333',
      borderRadius: 10,
      alignSelf: 'center',
      margin: Spacing.md,
      gap: Spacing.xs,
    },
  });
};
